# 🔢 NumPy Data Structures

---

## 📐 Vector

```python
[1, 2, 3, 4, 5, 6]
```

> A **one-dimensional** array of numbers

---

## 🔲 Matrix

```python
[[1, 2],
 [3, 4]]
```

> A **two-dimensional** array with rows and columns

---

## 🧊 Tensors

```python
[[[1, 2], [3, 4]],
 [[5, 6], [7, 8]]]
```

> **Multi-dimensional** arrays (3D and beyond)

---

### 💡 Quick Overview

| Type | Dimensions | Example |
|------|------------|---------|
| **Vector** | 1D | `[1, 2, 3, 4, 5, 6]` |
| **Matrix** | 2D | `[[1, 2], [3, 4]]` |
| **Tensors** | 3D+ | Multi-dimensional arrays |

# 🚀 NumPy Learning Journey

---

## 📍 PHASE 1: Foundation

> **NumPy Arrays and Basics**

---

In [3]:
import numpy as np

## 🎯 Creating Array from List
```python
# Convert a Python list to NumPy array
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
```

> Transform Python lists into powerful NumPy arrays

---

In [4]:
arr_1d = np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [6]:
arr_2d = np.array([[1,2], [3,4]])
arr_2d

array([[1, 2],
       [3, 4]])

## ⚖️ List vs NumPy Array

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| **Speed** | Slower ⏱️ | ⚡ Faster (50-100x) |
| **Memory** | More memory usage | 💾 Compact & efficient |
| **Operations** | Limited | Mathematical operations |
| **Type** | Mixed types allowed | Homogeneous (same type) |
| **Syntax** | Basic operations | Vectorized operations |

> NumPy arrays are optimized for numerical computations

---

### 🔄 Behavior Comparison

#### Python List - Concatenation
```python
py_list = [1, 2, 3]
py_list *= 2
py_list  # Output: [1, 2, 3, 1, 2, 3]
```
> Lists **repeat** elements when multiplied

---

#### NumPy Array - Element-wise Operation
```python
np_array = np.array([1, 2, 3])
np_array *= 2
np_array  # Output: [2, 4, 6]
```
> Arrays perform **mathematical operations** on each element

---

### ⏱️ Performance Comparison
```python
import time

# List operation
start = time.time()
py_list = list(range(1000000))
result = [x * 2 for x in py_list]
print(f"List time: {time.time() - start:.4f}s")

# NumPy operation
start = time.time()
np_array = np.arange(1000000)
result = np_array * 2
print(f"NumPy time: {time.time() - start:.4f}s")
```

> 💡 **NumPy is significantly faster** for large-scale numerical operations!

---

## 🔨 Creating Array from Scratch

---

### `np.zeros()` - Array of Zeros
```python
zeroes = np.zeros((3, 4))
zeroes
# Output: [[0. 0. 0. 0.]
#          [0. 0. 0. 0.]
#          [0. 0. 0. 0.]]
```
> Creates a **3×4 array** filled with zeros

---

### `np.ones()` - Array of Ones
```python
ones = np.ones((2, 3))
ones
# Output: [[1. 1. 1.]
#          [1. 1. 1.]]
```
> Creates a **2×3 array** filled with ones

---

### `np.full()` - Array with Custom Value
```python
full = np.full((2, 2), 7)
full
# Output: [[7 7]
#          [7 7]]
```
> Creates a **2×2 array** filled with **7**

---

### `np.random.random()` - Random Values
```python
randoms = np.random.random((2, 3))
randoms
# Output: [[0.234 0.876 0.123]
#          [0.987 0.456 0.789]]
```
> Creates a **2×3 array** with random values between **0 and 1**

---

### `np.arange()` - Sequence with Steps
```python
sequence = np.arange(0, 11, 3)  # (start, stop, step)
sequence
# Output: [0 3 6 9]
```
> Creates a sequence from **0 to 10** with a **step of 3**

---

## 🔢 Vector, Matrix, Tensors

---

### 📐 Vector (1D Array)
```python
vector = np.array([1, 2, 3])
vector
# Output: [1 2 3]
```
> A **one-dimensional** array

---

### 🔲 Matrix (2D Array)
```python
matrix = np.array([[1, 2], [3, 4]])
matrix
# Output: [[1 2]
#          [3 4]]
```
> A **two-dimensional** array with rows and columns

---

### 🧊 Tensor (3D Array)
```python
tensor = np.array([[[1, 2], [3, 4]], [[4, 5], [6, 7]]])
tensor
# Output: [[[1 2]
#           [3 4]]
#
#          [[4 5]
#           [6 7]]]
```
> A **multi-dimensional** array (3D and beyond)

---

### 💡 Quick Reference

| Type | Dimensions | Shape | Example |
|------|------------|-------|---------|
| **Vector** | 1D | `(3,)` | `[1, 2, 3]` |
| **Matrix** | 2D | `(2, 2)` | `[[1, 2], [3, 4]]` |
| **Tensor** | 3D+ | `(2, 2, 2)` | `[[[1, 2], [3, 4]], [[4, 5], [6, 7]]]` |

---

## 📊 Array Properties

---

### Understanding Core Properties
```python
arr = np.array([1, 2, 3])
```

---

#### 🔷 `shape` - Dimensions of the Array
```python
arr.shape
# Output: (3,)
```
> **Shape** tells you the size along each dimension  
> `(3,)` means 3 elements in a 1D array

---

#### 🔷 `ndim` - Number of Dimensions
```python
arr.ndim
# Output: 1
```
> **ndim** tells you how many dimensions (axes) the array has  
> `1` means it's a 1D array (vector)

---

#### 🔷 `size` - Total Number of Elements
```python
arr.size
# Output: 3
```
> **size** tells you the total count of elements  
> `3` means there are 3 elements in total

---

#### 🔷 `dtype` - Data Type of Elements
```python
arr.dtype
# Output: dtype('int64')
```
> **dtype** tells you the data type of array elements  
> `int64` means 64-bit integers

---

### 🧪 Type Conversion Examples

#### Mixed Integer and Boolean
```python
arr_2 = np.array([1, 2, True])
arr_2
# Output: [1 2 1]

arr_2.dtype
# Output: dtype('int64')
```
> ✅ **Works!** Boolean `True` converts to `1`, all become integers

---

#### Mixed Float, Integer, and Boolean
```python
arr_3 = np.array([1, 4.5, True])
arr_3
# Output: [1.  4.5 1. ]

arr_3.dtype
# Output: dtype('float64')
```
> ✅ **Works!** All values convert to float (highest precision type)

---

### 📋 Complete Example Breakdown
```python
matrix = np.array([[1, 2, 3], [4, 5, 6]])

matrix.shape   # (2, 3)    → 2 rows, 3 columns
matrix.ndim    # 2         → 2 dimensions (matrix)
matrix.size    # 6         → 6 total elements
matrix.dtype   # int64     → 64-bit integers
```

---

### 💡 Quick Reference Table

| Property | What it tells you | Example Output |
|----------|-------------------|----------------|
| **shape** | Size along each dimension | `(3,)` or `(2, 3)` |
| **ndim** | Number of dimensions | `1`, `2`, `3` |
| **size** | Total element count | `6`, `12` |
| **dtype** | Data type of elements | `int64`, `float64` |

---

### 🎯 Key Takeaway

> NumPy automatically converts mixed types to the **most general type** to maintain array homogeneity!

---

## 🔄 Array Reshaping

---

### Creating the Array
```python
arr = np.arange(12)
arr
# Output: [0 1 2 3 4 5 6 7 8 9 10 11]
```
> Creates a 1D array with values from **0 to 11**

---

### 📐 `reshape()` - Change Array Dimensions
```python
reshaped = arr.reshape((3, 4))
reshaped
# Output: [[ 0  1  2  3]
#          [ 4  5  6  7]
#          [ 8  9 10 11]]
```
> **Reshape** transforms the array into a new shape without changing data  
> Converts `(12,)` → `(3, 4)` (3 rows × 4 columns)

---

### 📏 `flatten()` - Convert to 1D (Copy)
```python
flattened = reshaped.flatten()
flattened
# Output: [0 1 2 3 4 5 6 7 8 9 10 11]
```
> **Flatten** converts multi-dimensional array to 1D  
> Creates a **new copy** of the data

---

### 📏 `ravel()` - Convert to 1D (View)
```python
raveled = reshaped.ravel()
raveled
# Output: [0 1 2 3 4 5 6 7 8 9 10 11]
```
> **Ravel** also converts to 1D array  
> Returns a **view** (reference) when possible, not a copy

---

### 🔃 `T` - Transpose (Flip Rows ↔ Columns)
```python
transpose = reshaped.T
transpose
# Output: [[ 0  4  8]
#          [ 1  5  9]
#          [ 2  6 10]
#          [ 3  7 11]]
```
> **Transpose** swaps rows and columns  
> Shape changes from `(3, 4)` → `(4, 3)`

---

### 💡 Quick Comparison

| Method | What it does | Creates Copy? | Shape Change |
|--------|--------------|---------------|--------------|
| **reshape()** | Changes dimensions | No (view) | `(12,)` → `(3, 4)` |
| **flatten()** | Converts to 1D | ✅ Yes | `(3, 4)` → `(12,)` |
| **ravel()** | Converts to 1D | ❌ No (view) | `(3, 4)` → `(12,)` |
| **T** | Swaps rows/columns | No (view) | `(3, 4)` → `(4, 3)` |

---

### 🎯 Key Difference: `flatten()` vs `ravel()`

> **flatten()** creates a new copy (safer, uses more memory)  
> **ravel()** creates a view (faster, shares memory with original)

---